#include "../include/Questions.h"

string AnswersGeography[50][4]
{

        {"Sydney", "Melbourne", "Canberra", "Brisbane"},
        {"Amazon", "Nile", "Yangtze", "Mississippi"},
        {"Sahara", "Gobi", "Arabian", "Kalahari"},
        {"Mount Kilimanjaro", "Mount Everest", "K2", "Mount Fuji"},
        {"Monaco", "Vatican City", "Nauru", "Liechtenstein"},
        {"Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Southern Ocean"},
        {"China", "Japan", "South Korea", "Vietnam"},
        {"Toronto", "Vancouver", "Ottawa", "Montreal"},
        {"Australia", "Brazil", "Indonesia", "Philippines"},
        {"Africa", "South America", "Antarctica", "Europe"},
        {"Rio de Janeiro", "Brasília", "Sao Paulo", "Salvador"},
        {"Paris", "Rome", "Venice", "Vienna"},
        {"Danube", "Volga", "Rhine", "Seine"},
        {"Norway", "Finland", "Sweden", "Iceland"},
        {"Africa", "Asia", "North America", "South America"},
        {"Sicily", "Sardinia", "Crete", "Cyprus"},
        {"Kenya", "Tanzania", "Uganda", "Ethiopia"},
        {"Arctic Ocean", "Southern Ocean", "Indian Ocean", "Atlantic Ocean"},
        {"Madrid", "Barcelona", "Seville", "Valencia"},
        {"Pacific Ocean", "Red Sea", "Caribbean Sea", "Baltic Sea"},
        {"Canada", "Russia", "China", "United States"},
        {"Kenya and Uganda", "Tanzania and Burundi", "Kenya and Ethiopia", "Tanzania and Ethiopia"},
        {"5,000 miles", "10,000 miles", "2,000 miles", "15,000 miles"},
        {"New York City", "Los Angeles", "Chicago", "Houston"},
        {"Brazil", "Colombia", "Vietnam", "Ethiopia"},
        {"Iceland", "Greenland", "Norway", "New Zealand"},
        {"South America", "Africa", "Europe", "North America"},
        {"Europe and Asia", "Africa and Europe", "Asia and Africa", "Europe and Africa"},
        {"Thames", "Seine", "Danube", "Rhine"},
        {"Johannesburg", "Cape Town", "Durban", "Pretoria"},
        {"Angel Falls", "Victoria Falls", "Iguazu Falls", "Niagara Falls"},
        {"China", "India", "United States", "Indonesia"},
        {"China", "Japan", "South Korea", "Taiwan"},
        {"Buenos Aires", "Santiago", "Lima", "Bogotá"},
        {"Israel and Jordan", "Israel and Egypt", "Israel and Syria", "Jordan and Egypt"},
        {"Rwanda", "Burundi", "Uganda", "Kenya"},
        {"Sydney", "Melbourne", "Brisbane", "Perth"},
        {"Rome", "Milan", "Florence", "Venice"},
        {"Russia", "Mongolia", "Kazakhstan", "China"},
        {"Venice", "Amsterdam", "Bruges", "Stockholm"},
        {"Amazon", "Paraná", "Orinoco", "Magdalena"},
        {"Maldives", "Seychelles", "Sri Lanka", "Mauritius"},
        {"Bangkok", "Hanoi", "Jakarta", "Kuala Lumpur"},
        {"Japan", "China", "South Korea", "Vietnam"},
        {"Danube", "Seine", "Rhine", "Tiber"},
        {"Gobi", "Arabian", "Thar", "Karakum"},
        {"Paris", "Marseille", "Lyon", "Nice"},
        {"New Zealand", "Iceland", "Norway", "Finland"},
        {"Egypt", "Morocco", "Tunisia", "Algeria"},
        {"Mexico City", "Cancun", "Guadalajara", "Monterrey"}

};
string AnswersMath[50][4] =
{
        {"3", "4", "5", "6"},
        {"2", "3", "4", "5"},
        {"3", "3.14", "4", "2"},
        {"45°", "90°", "180°", "360°"},
        {"10", "25", "30", "40"},
        {"8", "11", "12", "15"},
        {"2", "4", "6", "8"},
        {"10", "12", "14", "16"},
        {"3", "4", "5", "6"},
        {"5", "10", "15", "20"},
        {"50", "60", "70", "100"},
        {"90°", "180°", "270°", "360°"},
        {"3", "4", "5", "6"},
        {"1/3", "2/4", "3/6", "4/8"},
        {"10 units", "15 units", "20 units", "25 units"},
        {"10", "50", "100", "1000"},
        {"8 square units", "12 square units", "24 square units", "32 square units"},
        {"6", "9", "12", "15"},
        {"1", "2", "3", "4"},
        {"4", "5", "6", "7"},
        {"0.25", "0.50", "0.75", "1.00"},
        {"2", "3", "3.5", "4"},
        {"20", "25", "30", "36"},
        {"10", "100", "1000", "10000"},
        {"10", "25", "35", "42"},
        {"10", "20", "50", "100"},
        {"Circle", "Triangle", "Square", "Rectangle"},
        {"45", "50", "55", "60"},
        {"90°", "180°", "270°", "360°"},
        {"20", "24", "28", "32"},
        {"5", "6", "7", "8"},
        {"25%", "50%", "75%", "100%"},
        {"180°", "270°", "360°", "450°"},
        {"42", "45", "48", "54"},
        {"1", "2", "3", "5"},
        {"20", "24", "32", "64"},
        {"14", "16", "20", "22"},
        {"7", "8", "9", "10"},
        {"3", "4", "5", "6"},
        {"1/6", "1/3", "2/3", "1"},
        {"10", "100", "1000", "10000"},
        {"7 square units", "14 square units", "21 square units", "49 square units"},
        {"12", "17", "20", "27"},
        {"12", "15", "18", "21"},
        {"5", "8", "9", "12"},
        {"1/2", "2/5", "3/4", "5/8"},
        {"6", "7", "8", "9"},
        {"6", "7", "8", "9"},
        {"4", "6", "8", "10"},
        {"50", "60", "70", "90"}
};


string AnswersEnglish[50][4] =
{
        {"London", "Paris", "Berlin", "Madrid"},
        {"Jupiter", "Venus", "Mars", "Saturn"},
        {"Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Michelangelo"},
        {"Wa", "Wo", "Wa2", "H2O"},
        {"Harper Lee", "Mark Twain", "F. Scott Fitzgerald", "William Faulkner"},
        {"Indian Ocean", "Atlantic Ocean", "Pacific Ocean", "Arctic Ocean"},
        {"Avocado", "Tomato", "Onion", "Lemon"},
        {"Au", "Ag", "Go", "Gu"},
        {"Netherlands", "Italy", "France", "Germany"},
        {"William Shakespeare", "Charles Dickens", "Jane Austen", "George Orwell"},
        {"Hippopotamus", "Giraffe", "Elephant", "Rhino"},
        {"Earth", "Venus", "Mercury", "Mars"},
        {"Tokyo", "Beijing", "Seoul", "Bangkok"},
        {"Leonardo da Vinci", "Raphael", "Michelangelo", "Donatello"},
        {"Dollar", "Euro", "Pound", "Yen"},
        {"Heart", "Liver", "Skin", "Brain"},
        {"Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Alan Shepard"},
        {"O", "Ox", "Om", "H2O"},
        {"Gold", "Diamond", "Iron", "Quartz"},
        {"Jane Austen", "Emily Bronte", "Charlotte Bronte", "George Eliot"},
        {"Elephant", "Blue whale", "Hippopotamus", "Giraffe"},
        {"Chickpeas", "Tomato", "Onion", "Lemon"},
        {"Vincent van Gogh", "Pablo Picasso", "Claude Monet", "Salvador Dali"},
        {"Rome", "Milan", "Florence", "Naples"},
        {"Ag", "Si", "S", "Sl"},
        {"Europe", "Africa", "Asia", "North America"},
        {"George Orwell", "Aldous Huxley", "J.D. Salinger", "F. Scott Fitzgerald"},
        {"Brasília", "Rio de Janeiro", "São Paulo", "Salvador"},
        {"Ca", "C", "Co", "Cr"},
        {"Jupiter", "Saturn", "Neptune", "Mars"},
        {"F. Scott Fitzgerald", "Ernest Hemingway", "John Steinbeck", "William Faulkner"},
        {"Toronto", "Montreal", "Ottawa", "Vancouver"},
        {"He", "H", "Hy", "Hel"},
        {"Cheetah", "Lion", "Gazelle", "Leopard"},
        {"Marie Curie", "Rosa Parks", "Mother Teresa", "Margaret Thatcher"},
        {"Ni", "N", "Na", "Ne"},
        {"Mount Everest", "K2", "Kangchenjunga", "Lhotse"},
        {"William Shakespeare", "Geoffrey Chaucer", "John Milton", "Dante Alighieri"},
        {"Sydney", "Melbourne", "Canberra", "Brisbane"},
        {"S", "So", "Na", "Ni"},
        {"Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"},
        {"Sahara Desert", "Gobi Desert", "Antarctic Desert", "Arabian Desert"},
        {"Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"},
        {"K", "Po", "P", "Ka"},
        {"Peregrine Falcon", "Ostrich", "Hummingbird", "Swift"},
        {"J.D. Salinger", "Harper Lee", "John Steinbeck", "Ernest Hemingway"},
        {"Shanghai", "Beijing", "Guangzhou", "Hong Kong"},
        {"Ir", "Fe", "In", "I"},
        {"Ostrich", "Eagle", "Albatross", "Emu"},
        {"J.R.R. Tolkien", "C.S. Lewis", "George R.R. Martin", "J.K. Rowling"},
};

map<int, const char*> QuestionsMath =
{
        {1, "2 + 2?"},
        {2, "Triangle sides?"},
        {3, "Value of pi?"},
        {4, "Degrees in a right angle?"},
        {5, "5 x 6?"},
        {6, "Prime number?"},
        {7, "Square root of 16?"},
        {8, "Next in 2, 4, 6, 8, ...?"},
        {9, "Square sides?"},
        {10, "10% of 50?"},
        {11, "Minutes in an hour?"},
        {12, "Sum of triangle angles?"},
        {13, "9 - 4?"},
        {14, "Equivalent to 1/2?"},
        {15, "Perimeter of a square with sides 5?"},
        {16, "Cm in a meter?"},
        {17, "Area of 8x4 rectangle?"},
        {18, "3 squared?"},
        {19, "Composite number?"},
        {20, "Sides of a pentagon?"},
        {21, "3/4 as decimal?"},
        {22, "7 / 2?"},
        {23, "Next in 1, 4, 9, 16, ...?"},
        {24, "Mm in a cm?"},
        {25, "Product of 5 and 7?"},
        {26, "10 squared?"},
        {27, "Shape with 3 sides?"},
        {28, "Sum of first 10 natural numbers?"},
        {29, "Degrees in a circle?"},
        {30, "12 + 20 - 8?"},
        {31, "Sides of a hexagon?"},
        {32, "1/4 as percentage?"},
        {33, "Sum of quadrilateral angles?"},
        {34, "6 x 9?"},
        {35, "Not a prime number?"},
        {36, "Next in 2, 4, 8, 16, ...?"},
        {37, "5^2 - 3^2?"},
        {38, "Sides of an octagon?"},
        {39, "15 / 3?"},
        {40, "Sum of 2/3 and 1/3?"},
        {41, "M in a km?"},
        {42, "Area of a square 7 units?"},
        {43, "4 x 3 + 5?"},
        {44, "Next in 1, 3, 6, 10, ...?"},
        {45, "Multiple of 4?"},
        {46, "0.5 as fraction?"},
        {47, "10 / 2 + 3?"},
        {48, "Sides of a heptagon?"},
        {49, "2^3?"},
        {50, "100 - 30 + 20?"}

};
map<int, const char*> QuestionsEnglish
{ 
        {1, "Capital of France?"},
        {2, "Red Planet?"},
        {3, "Painter of Mona Lisa?"},
        {4, "Chemical symbol for water?"},
        {5, "Author of 'To Kill a Mockingbird'?"},
        {6, "Largest ocean?"},
        {7, "Main ingredient in guacamole?"},
        {8, "Chemical symbol for gold?"},
        {9, "Country famous for tulips?"},
        {10, "Writer of 'Hamlet'?"},
        {11, "Tallest mammal?"},
        {12, "Smallest planet?"},
        {13, "Capital of Japan?"},
        {14, "Painter of Sistine Chapel ceiling?"},
        {15, "Currency of UK?"},
        {16, "Largest human organ?"},
        {17, "First man on moon?"},
        {18, "Chemical symbol for oxygen?"},
        {19, "Hardest natural substance?"},
        {20, "Author of 'Pride and Prejudice'?"},
        {21, "Largest mammal?"},
        {22, "Main ingredient in hummus?"},
        {23, "Painter of 'The Starry Night'?"},
        {24, "Capital of Italy?"},
        {25, "Chemical symbol for silver?"},
        {26, "Largest continent?"},
        {27, "Author of '1984'?"},
        {28, "Capital of Brazil?"},
        {29, "Chemical symbol for carbon?"},
        {30, "Largest planet?"},
        {31, "Writer of 'The Great Gatsby'?"},
        {32, "Capital of Canada?"},
        {33, "Chemical symbol for helium?"},
        {34, "Fastest land animal?"},
        {35, "First woman Nobel Prize winner?"},
        {36, "Chemical symbol for nitrogen?"},
        {37, "Tallest mountain?"},
        {38, "Writer of 'Romeo and Juliet'?"},
        {39, "Capital of Australia?"},
        {40, "Chemical symbol for sodium?"},
        {41, "Painter of 'The Last Supper'?"},
        {42, "Largest desert?"},
        {43, "Inventor of telephone?"},
        {44, "Chemical symbol for potassium?"},
        {45, "Fastest bird?"},
        {46, "Author of 'The Catcher in the Rye'?"},
        {47, "Capital of China?"},
        {48, "Chemical symbol for iron?"},
        {49, "Largest bird?"},
        {50, "Writer of 'The Lord of the Rings'?"},
};

map<int, const char*> QuestionsGeography
{
        {1, "Capital of Australia?"},
        {2, "Longest river?"},
        {3, "Largest desert?"},
        {4, "Highest mountain?"},
        {5, "Smallest country?"},
        {6, "Largest ocean?"},
        {7, "Land of the Rising Sun?"},
        {8, "Capital of Canada?"},
        {9, "Great Barrier Reef country?"},
        {10, "Dark Continent?"},
        {11, "Capital of Brazil?"},
        {12, "City of Love?"},
        {13, "Longest river in Europe?"},
        {14, "Land of Midnight Sun?"},
        {15, "Strait of Gibraltar continent?"},
        {16, "Largest Mediterranean island?"},
        {17, "Mount Kilimanjaro country?"},
        {18, "Smallest ocean?"},
        {19, "Capital of Spain?"},
        {20, "Panama Canal connect?"},
        {21, "Largest country?"},
        {22, "Lake Victoria countries?"},
        {23, "Great Wall of China length?"},
        {24, "Largest US city?"},
        {25, "Largest coffee producer?"},
        {26, "Land of Fire and Ice?"},
        {27, "Andes location?"},
        {28, "Istanbul continents?"},
        {29, "Paris river?"},
        {30, "Capital of South Africa?"},
        {31, "Tallest waterfall?"},
        {32, "Most populous country?"},
        {33, "Kyoto country?"},
        {34, "Capital of Argentina?"},
        {35, "Dead Sea countries?"},
        {36, "Land of Thousand Hills?"},
        {37, "Largest Australian city?"},
        {38, "Capital of Italy?"},
        {39, "Lake Baikal country?"},
        {40, "City of Canals?"},
        {41, "Longest South American river?"},
        {42, "Pearl of Indian Ocean?"},
        {43, "Capital of Thailand?"},
        {44, "Land of the Rising Sun?"},
        {45, "Budapest river?"},
        {46, "Largest Asian desert?"},
        {47, "Capital of France?"},
        {48, "Long White Cloud country?"},
        {49, "Marrakech country?"},
        {50, "Capital of Mexico?"}
};

